### ISSUE TITLE
Showkase for Epoxy?

### ISSUE THREAD

**Issue by sanogueralorenzo** [airbnb/Showkase#129]
Hello 👋 

Are there any plans to open source the Showkase annotation you have for Epoxy?

Trying to maintain design system components with epoxy in a showcase app has been challenging mostly for the manual work it involves (multiple permutations) and the organization it involves.

Thank you 🙏

**Comment by vinaygaba** [comment]
Sorry about missing this issue 😓 I've regularly work on and upgrade this repo but somehow missed seeing this. I think this is a reasonable request. We do have an internal version of the tool that provides support for classic Android & Epoxy (Showkase was inspired from it). Adding support for that to Showkase would be a good amount of work although I'm not opposed to it. I'm curious to see how many people are actually interested in seeing this given that Compose seems to be where things are headed.

**Comment by sanogueralorenzo** [comment]
Thanks for the reply!

My idea was more having a new library `Showpoxy` 😄 but yeah I agree, it is a bit late asking for this since Compose is around the corner and if it is internal and not easy to open source there is no problem, completely understand.

Will definitely integrate Showkase when we start migrating to Compose!
