### ISSUE TITLE
Dark mode demo not working

### ISSUE THREAD

**Issue by alorma** [airbnb/Showkase#135]
![Captura de pantalla 2021-03-08 a las 9 26 04](https://user-images.githubusercontent.com/887462/110294625-5f23ea80-7ff0-11eb-971e-6190d5bf6c24.png)

Hi.

I'm using this code to change (and animate) dark mode from a debug drawer:

```
@Composable
fun RestaurantMenuNumbersTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    darkThemeState: MutableState<Boolean> = remember { mutableStateOf(darkTheme) },
    content: @Composable (MutableState<Boolean>) -> Unit,
) {

    val transition = updateTransition(targetState = darkThemeState.value)

    val colors = if (darkThemeState.value) {
        DarkColorPalette
    } else {
        LightColorPalette
    }

    val animateColors = Colors(
        primary = transition.animateColor { colors.primary }.value,
        primaryVariant = transition.animateColor { colors.primaryVariant }.value,
        secondary = transition.animateColor { colors.secondary }.value,
        secondaryVariant = transition.animateColor { colors.secondaryVariant }.value,
        background = transition.animateColor { colors.background }.value,
        surface = transition.animateColor { colors.surface }.value,
        error = transition.animateColor { colors.error }.value,
        onPrimary = transition.animateColor { colors.onPrimary }.value,
        onSecondary = transition.animateColor { colors.onSecondary }.value,
        onBackground = transition.animateColor { colors.onBackground }.value,
        onSurface = transition.animateColor { colors.onSurface }.value,
        onError = transition.animateColor { colors.onError }.value,
        isLight = colors.isLight,
    )

    MaterialTheme(
        colors = animateColors,
        typography = Typography,
        shapes = Shapes,
        content = { content(darkThemeState) }
    )
}
```

So, showkase not shows the dark mode / l right mode correctly

**Comment by vinaygaba** [comment]
Hey @alorma! Thank you for reporting this. Can I ask you a couple follow up questions - 

- How are you enabling the dark mode from the debug menu. Could you point me to the code that you are using?
- Which Android API version was your emulator/device using?

**Comment by vinaygaba** [comment]
@alorma Actually, I have a feeling that if you just display this component on the screen and then toggle dark mode through the system settings, this component will not be updated. Can you try doing that and report your findings?

**Comment by alorma** [comment]
Uhmm, you are right.

I've used this code to change dark mode from drawer, using a state with `isSystemDark()` as an initial value:

https://github.com/alorma/Restaurant-Menu-numbers/blob/main/app/src/main/java/com/alorma/menunumbers/ui/base/modules/DarkThemeModule.kt

**Comment by alorma** [comment]
I've removed my custom code for do weird things with dark mode.

But, as now is the same as provided by default template... it says the same, dark and light versions are the same color :S

![Captura de pantalla 2021-03-09 a las 8 58 35](https://user-images.githubusercontent.com/887462/110437403-a32cf300-80b5-11eb-9925-5838ee8a1377.png)

**Comment by vinaygaba** [comment]
@alorma Which Android API is running on your device/emulator? I was able to see the dark mode correctly with the exact code that you shared when you posted this issue :O

**Comment by alorma** [comment]
Android 29, just an emulator

**Comment by vinaygaba** [comment]
Here's what I see when I used the `RestaurantMenuNumbersTheme` composable.

<img width="471" alt="Screen Shot 2021-03-08 at 10 23 58 PM" src="https://user-images.githubusercontent.com/4281910/110440672-ff175d80-805c-11eb-848a-39a816149d95.png">

I think I might have a clue about what's going on. So copy paste the following code and give it a shot - 

```kotlin
@ShowkaseComposablel(name = "Name", group = "Group")
@Composable
fun testPreview() {
    RestaurantMenuNumbersTheme {
        Surface(modifier = Modifier.fillMaxWidth().height(200.dp)) {
            Text("Hello World")
        }
    }
}

```

Can you give it a shot and post a screenshot of what this component looks like in Showkase. This should work!

**Comment by alorma** [comment]
![Captura de pantalla 2021-03-09 a las 17 33 46](https://user-images.githubusercontent.com/887462/110504591-9c29d300-80fd-11eb-9a98-4fa9152106a9.png)

**Comment by vinaygaba** [comment]
@alorma And what do you see on the next screen which also show the permutations of this component?

**Comment by alorma** [comment]
Oh sorry, my bad

**Comment by alorma** [comment]
Uhm, that's weird...

![Screenshot_20210309_181700](https://user-images.githubusercontent.com/887462/110510602-a949c080-8103-11eb-8b51-3d2c9a067838.png)

**Comment by vinaygaba** [comment]
@alorma This worked as expected yeah? The reason why your original example might not be working is because the `content` that you passed to `RestaurantMenuNumbersTheme` wasn't using colors from the theme. If you changed that, dark mode will start working as expected. In my example, because I wrapped my `Text` inside a `Surface`, those composables have logic to directly use the MaterialTheme for styling if nothing is provided. Hence my example works correctly. Does that make sense?

**Comment by alorma** [comment]
Uhmm, but the original example is just a floating button and using it by default...

**Comment by vinaygaba** [comment]
@alorma So I see that FAB uses the `secondary` color as its background. When I looked at the default dark and light color palettes, I noticed that they use the same color - `0xFF03DAC6`. Hence the color does not change.

**Comment by alorma** [comment]
Sorry... I'm losing something...

```kotlin
val LightColorPalette = lightColors(
    secondary = soda,
)
val soda = Color(0xFFff6340)

val DarkColorPalette = darkColors(
    secondary = soda_l_3,
)
val soda_l_3 = Color(0xFFffd7cf)
```

So, both `secondary` colors are different.

Also, I have to previews, one light and one dark, and this is the result:

<img width="120" alt="Captura de pantalla 2021-03-09 a las 20 45 12" src="https://user-images.githubusercontent.com/887462/110528455-76f68e00-8118-11eb-9544-9e94a2e470d6.png">
<img width="120" alt="Captura de pantalla 2021-03-09 a las 20 45 22" src="https://user-images.githubusercontent.com/887462/110528462-7827bb00-8118-11eb-8fdb-034425080ebc.png">
<img width="120" alt="Captura de pantalla 2021-03-09 a las 20 45 28" src="https://user-images.githubusercontent.com/887462/110528467-7827bb00-8118-11eb-8fbe-55a871209475.png">

What I'm missing?

**Comment by vinaygaba** [comment]
I think this is because in the last screenshot,  you have enabled dark mode system wide. That forces the other previews to also render what its supposed to render in dark mode. Was dark mode enabled system wide when you took the 3rd screenshot? @alorma

**Comment by alorma** [comment]
Uhmmm, I think yes ... but no worry, feel free to close this issue
