### ISSUE TITLE
Showkase scaffold UI

### ISSUE THREAD

**Issue by alorma** [airbnb/Showkase#136]
Hi.

Just wondering, why not using scaffold and TopAppBar to have a better material "look" on showkase, and instead show a custom top bar

![Captura de pantalla 2021-03-09 a las 17 35 09](https://user-images.githubusercontent.com/887462/110504785-cc717180-80fd-11eb-85f8-71f5699c5dab.png)

**Comment by vinaygaba** [comment]
That used to be the case until the last release. There are some issues with Compose beta01. This is the code where I had to comment it - https://github.com/airbnb/Showkase/pull/130/files#diff-b30e56106f28f96c55285c2222abafe8741686b67e5e1de440160e5b6aa7a302R112

Related conversation - https://kotlinlang.slack.com/archives/CJLTWPH7S/p1614749703084000
