### ISSUE TITLE
Component browser crashes when using Compose-beta04

### ISSUE THREAD

**Issue by benkay** [airbnb/Showkase#147]
The implemention of the inline `Row` function changed in beta04, and now when trying to open the browser in a project compiled with the latest Compose version it immediately crashes with `java.lang.NoSuchFieldError: No static field Companion of type Landroidx/compose/foundation/layout/RowScope$Companion; in class Landroidx/compose/foundation/layout/RowScope; or its superclasses`

The fix should be to just bump the Compose version in the library to the latest (I suppose beta05 should drop today)

**Comment by vinaygaba** [comment]
I'll do a release tomorrow with the latest version of Compose and that should most likely fix this like you recommended!

**Comment by vinaygaba** [comment]
Latest release is out - https://github.com/airbnb/Showkase/releases/tag/1.0.0-alpha10
This should fix the issue :) Let me know if it doesn't!
