### ISSUE TITLE
Update to target latest Compose version?

### ISSUE THREAD

**Issue by Dambakk** [airbnb/Showkase#151]
Hi! 

Compose Beta-08 just came out! Showkase currently targets beta-05. Are there any plans to update this library to target the latest version?

**Comment by vinaygaba** [comment]
Someone opened up a PR for the latest version - https://github.com/airbnb/Showkase/pull/152#pullrequestreview-675429080

Will be doing a release today as soon as that merged

**Comment by vinaygaba** [comment]
The latest version of Showkase just released and that takes care of this issue 🎉 

https://github.com/airbnb/Showkase/releases/tag/1.0.0-alpha11
