### ISSUE TITLE
Duplicate classes when building multiple sub modules

### ISSUE THREAD

**Issue by HugoAlberto** [airbnb/Showkase#169]
Hi ! 
I've run into an issue when setting the kapt showkase processor in multiple sub modules in our project.
Works fine with a main module and one sub module but not anymore when adding another one.

```
Execution failed for task ':application:mergeLibDexDevelopmentDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.airbnb.android.showkase.LiveLiterals$ShowkaseMetadataUiKt is defined multiple times: 

C:\Users\xxx\Documents\projects\xxx\feature\schedules\build\.transforms\761e96e2c30a858d67dede619ffe9cac\transformed\classes\classes.dex, 
C:\Users\xxx\Documents\projects\xxx\feature\marketplace\build\.transforms\2a25bfd32f11783abb2a278e250a60d6\transformed\classes\classes.dex
```

Library is a really good idea btw so good job on that !

As a side note, to give you some feedback of our usage of it : 
Our project add feature modules on the fly depending of the app configuration and resolve them with DI at runtime. So the implementation : Root module that have it's children doesn't work for us. 
To make it work, I did a showkase module where the root annotation is, and that implement all the other compose modules when building in debug. If a better way exist, i'll be glad to know it !

Thanks for your time and the library again.

**Comment by HugoAlberto** [comment]
So it seems it's not much of a big deal !
All previews in our project modules are all located in a `ui` package !

I made it work by taking more than the last `packageSimpleName` and the whole package name in the `ShowkaseCodegenMetadataWriter.kt` file.

**Comment by vinaygaba** [comment]
@HugoAlberto Can you share what exactly you change to fix the issue for yourself?

**Comment by HugoAlberto** [comment]
In this file : https://github.com/airbnb/Showkase/blob/645af2ec6e754feaf58aac1fa6a6e6ec1e33c741/showkase-processor/src/main/java/com/airbnb/android/showkase/processor/writer/ShowkaseCodegenMetadataWriter.kt#L22

I replaced with this :
`val moduleName = showkaseMetadataSet.first().packageName.replace('.', '_')`

The generated class name may not be formatted like you want but it was a quick fix as the full package name will not be duplicated for the 4 ui submodules we have in the project right now.

**Comment by vinaygaba** [comment]
I see! I think this is something I can fix in the library itself. I intended to use the whole package name itself and am surprised that it was only taking a part of the package. I will experiment at bit and fix it if I notice that that's not happening.

**Comment by vinaygaba** [comment]
This has been fixed with this PR - https://github.com/airbnb/Showkase/commit/794af71cc6b70d6a2bdde1ffe642fbeb7c1d0f0a
