### ISSUE TITLE
app_name string is overridden by Showkase

### ISSUE THREAD

**Issue by guk-ioki** [airbnb/Showkase#173]
The file [showkase/src/main/res/values/strings.xml](https://github.com/airbnb/Showkase/blob/master/showkase/src/main/res/values/strings.xml) contains a string with the key `app_name` and the value `Showkase`.

Through manifest merging, this ends up overwriting our app's name in the manifest file.

I don't see a case for this string to exist in Showkase at all 🤔

**Comment by vinaygaba** [comment]
Thanks for submitting the PR for this!
