### ISSUE TITLE
Question/Feature Request: A way to showcase custom data structures/themes

### ISSUE THREAD

**Issue by Dambakk** [airbnb/Showkase#181]
Hi! 

In our app we have many similar screens with different themes. I'm planning to use composition locals to decide which colors to use, kinda like this:

```
data class LobbyColors(
  val a: Color,
  val b: Color,
  ...
)

val lotteryA = LobbyColors(
  a = ...,
  b = ...,
)

val lotteryB = LobbyColors(
  a = ...,
  b = ...,
)
```

I would like to get a preview of these different configurations (e.g Showkase -> Colors -> LotteryA -> all colors defined in `lotteryA`). How can I do that? Or if not possible, consider this a feature request :)

**Comment by vinaygaba** [comment]
This is effectively a dupe of #171 so closing in favor of the other ticket and will plan on adding support soon!
