### ISSUE TITLE
Question: push custom data

### ISSUE THREAD

**Issue by alivDev1** [airbnb/Showkase#190]
Hello, i have a custom data class for typography which holds its name, xml resource id and compose value. Is it possible to push custom data to the showkase gallery ? like i have a list of my objects which I can map to typography and would be nice something like ShowKase.addTypography

We currently have a list of this data class

```
    data class TextStyle(
        val styleXml: Int,
        val styleCompose: androidx.compose.ui.text.TextStyle,
        val displayName: String
    )
```

which can be actually modified runtime since its a UI library we are building for our products, a workaround might seems like just putting those styles into an object and reference them, but it would not work if it changes runtime in a specific app

**Comment by alivDev1** [comment]
Hello, any update on this ? I think its a nice improvement on dynamic color/typografy systems. Simple soution could just expose a singleton object with 3 lists like

```
object ShowkaseCustomData{
             var   customGroupedComponentsList,
              var  customGroupedColorsList,
               var  customGroupedTypographyList
}

then they could be displayed together

ShowkaseBrowserActivity:
            val (
                groupedComponentsList,
                groupedColorsList,
                groupedTypographyList
            ) = getShowkaseProviderElements(classKey) + our custom lists
```

Usage would be simple as
ShowkaseCustomData.customGroupedColorsList.add(listOfCustomColors)
 activity.startActivity(Showkase.getBrowserIntent(activity))

**Comment by vinaygaba** [comment]
I think for custom use cases like this, it would be better to just create your own  custom browser as Showkase already exposes all the metadata it has through the `Showkase.getMetadata()` API call. More information here - https://github.com/airbnb/Showkase#5-showkase-object. So in theory it should be trivial to create a UI for your use case using the metadata that Showkase exposes.
