### ISSUE TITLE
Generated code is stale

### ISSUE THREAD

**Issue by aachatz-bc** [airbnb/Showkase#193]
I seem to need to manually go in and delete code from the code gen to get code to compile sometimes.

It seems like neither clean or invalidate caches+restart, actually cleans up the code gen.

**Comment by vinaygaba** [comment]
I think this might be from a known bug in incremental annotation processing. Hopefully KSP solves this. We just released KSP support so would love for you to try it and let us know if you are still seeing this issue - https://github.com/airbnb/Showkase/releases/tag/1.0.0-beta09

**Comment by mattbusuu** [comment]
Possibly related to https://github.com/airbnb/Showkase/issues/273 ?
