### ISSUE TITLE
Incorrect width and height when using @Preview annotation

### ISSUE THREAD

**Issue by ofalvai** [airbnb/Showkase#204]
When I'm using the `@Preview` annotation from Compose, my composables are rendered as tiny squares. They are rendered correctly when I switch to `@ShowkaseComposable`, but I want to restrict Showkase dependencies to `debugImplementation` only, so I don't want to import `@ShowkaseComposable` in any production files.

Looking at the generated code of one `@Preview` annotated and one `@ShowkaseComposable` annotated function, the only difference is the `width` and `height` parameters:

```kotlin
        ShowkaseBrowserComponent(
            group = "Calendar",
            componentName = "Day legend",
            componentKDoc = "",
            componentKey = """...""",
            isDefaultStyle = false,
            widthDp = -1,
            heightDp = -1,
            component = @Composable { PreviewCalendarDayLegend() }),
        ShowkaseBrowserComponent(
            group = "Calendar",
            componentName = "Pager",
            componentKDoc = "",
            componentKey = """...""",
            isDefaultStyle = false,
            component = @Composable { PreviewCalendarPager() }),
```

Note: I'm using KSP instead of KAPT for code generation.

**Comment by vinaygaba** [comment]
Hmm I'll have to take a look at this. KSP is brand new so its possible that some logic could've unintentionally changed 🤔

**Comment by vinaygaba** [comment]
Also, I need to update some documentation that talks about how Showkase can be added only to the debug builds. I'll do it soon!

**Comment by andrey-bolduzev** [comment]
Can confirm, I'm seeing the same tiny white squares on beta 10 with kapt as well. Specifying `widthDp` and `heightDp` in the `@Preview` fixes the rendering but is not scalable.

**Comment by vinaygaba** [comment]
I have a fix up for it!
