### ISSUE TITLE
Multi-Module Sample

### ISSUE THREAD

**Issue by Chrisjc28** [airbnb/Showkase#205]
Please can there be a multi-module example added or more details to the documentation/read me currently trying to implement Showkase in a multi-module project but the getBrowserIntent is being generated separately for each module so i can see all of the components at once

**Comment by vinaygaba** [comment]
You need to have the ShowkaseRoot implementation only in your root module. It sounds like you might be adding ShowkaseRoot in every module. The current sample has a multi module setup itself. Look at `sample` and `sample-submodule` 

https://github.com/airbnb/Showkase/tree/master/sample
https://github.com/airbnb/Showkase/tree/master/sample-submodule
