### ISSUE TITLE
Conflicting overload

### ISSUE THREAD

**Issue by themanol** [airbnb/Showkase#206]
In our current project we have color definitions like that:

```
object DarkColors {
    object Red {
        @ShowkaseColor(name = "Red 800", group = "Dark Colors")
        val Red800 = Color(0xFFF5A89E)
        
```
        

and 

```
object LightColors {
    object Red {
        @ShowkaseColor(name = "Red 800", group = "Light Colors")
        val Red800 = Color(0xFF5C1905)
```

Because the writer metadata is using only the first enclosing class this is creating conflicting overload with the autogenerated code.

```
val methodName = when (val enclosingClass = showkaseMetadata.enclosingClassName) {
                null -> showkaseMetadata.elementName
                else -> {
                    "${enclosingClass.simpleName}_${showkaseMetadata.elementName}"
                }
            }
```

do you think that could be a good idea if instead of using the enclosing class and the element name change it by `showkaseMetadata.showkaseName` and `showkaseMetadata.showkaseGroup` and because they are unique it shouldn't create problems.

Thanks!

**Comment by vinaygaba** [comment]
This suggestion makes sense! Thank you for flagging. Do you want to throw in a PR that does this? I can take care of it too but I'd be happy to have more contributors 😅

Just as an FYI - after you make the changes, updating the test cases simply involves changing this boolean and running the tests locally - https://github.com/airbnb/Showkase/blob/master/showkase-processor-testing/src/test/java/com/airbnb/android/showkase_processor_testing/BaseProcessorTest.kt#L18. After that you revert the boolean back but keep the test changes that the script makes. Easy peasy!

**Comment by themanol** [comment]
I've created the PR, finally I had to check about the style too in case of components, because that is allow to have same name, group but different style. Thanks!
