### ISSUE TITLE
Integration with Paparazzi screenshot testing

### ISSUE THREAD

**Issue by marcorighini** [airbnb/Showkase#207]
Showkase is actually providing an integration with facebook screenshot testing. 
Is it possible to integrate Showkase with Paparazzi (screenshot testing without device, link https://github.com/cashapp/paparazzi)?

**Comment by vinaygaba** [comment]
Showkase itself doesn't provide any integrations (yet). The blog post that you probably saw(https://proandroiddev.com/automatic-screenshot-testing-for-all-your-compose-previews-6add202fecc7) used Showkase for the automated infra but then integrated it with Facebook's library. In theory, it can work with anything but you will have to do that setup today. I fully intend to provide a sample integration and expose it as an artifact at some point.

If you are interested, I'd be happy to accept a contribution that adds a Paparazzi integration submodule (or even Shot).

**Comment by davidvavra** [comment]
Wow, Paparazzi looks interesting. I'm not very happy with Facebook's library. It's not very maintained and it doesn't work for API 28+. If it runs without emulator, it can faster and a deal-breaker for CI integrations. Emulators on CI are pain to setup. I might try to play with Papparazi + Showkase in some free time.

**Comment by vinaygaba** [comment]
I think that's a Compose requirement itself. I haven't double checked this but that's what I always assumed.

**Comment by davidvavra** [comment]
Well, Papparazi has to do it somehow. They support snapshotting Views without instrumentation. They don't support Compose now, but they plan it for v1. But I'm assuming wrapping composables into Views might work. Might be worth investigating how they do it.

**Comment by marcorighini** [comment]
I started the integration of paparazzi 1.0.0 (snapshot, the version supporting compose) in https://github.com/marcorighini/Showkase/tree/paparazzi-screenshot-testing-integration

Still to investigate:
- codegen not run on `MyScreenshotTest` file (unit test file)
- remove `ComposeTestRule` from current codegen and assess if needs to be replaced with `Paparazzi` rule

**Comment by alexvanyo** [comment]
I was able to utilize Showkase's code generation to automatically populate Paparazzi tests by avoiding the `showkase-screenshot-testing` module.

Instead, I just pulled out the list of components (from `Showkase.getMetadata().componentList`), and used that as the input to a parameterized Paparazzi test, using the `componentKey` for the test name and `component` as the `@Composable` under test.

**Comment by vinaygaba** [comment]
@alexvanyo Very cool! I had initially taken the parameterized test route myself but eventually found a limitation that didn't allow us to use it with our setup. It was something to do with how the Firebase Test Lab was handling sharding iirc.

**Comment by alexvanyo** [comment]
Just curious, were you trying to run those Paparzzi + Showkase tests on device?
With Paparazzi, it can just be done off-device (with a parameterized test in `src/test`)

**Comment by vinaygaba** [comment]
@alexvanyo No I meant for the originally implementation of automated screenshot testing itself. It wasn't using Paparazzi then but I think this might be viable now that Paparazzi supports Compose.

**Comment by alexvanyo** [comment]
Ah gotcha, yeah parameterized testing doesn't play well with instrumented tests last time I checked, I am using https://github.com/google/TestParameterInjector for that.

**Comment by davidvavra** [comment]
@alexvanyo Great! Can you share some code sample? I would like to play around with it and maybe then publish some article/library for it. I would love to get rid of Android emulator in our CI setup, it is causing a lot of flakiness/slowness/maintanance.

**Comment by vinaygaba** [comment]
Just as an update to an earlier comment on this thread, I did push a PR that adds Shot integration as a new artifact - https://github.com/airbnb/Showkase/pull/232. This should give you an end-to-end working solution for screenshot testing. Would love to have a similar artifact for Paparazzi as well...

**Comment by alexvanyo** [comment]
https://gist.github.com/alexvanyo/c4d2b6530f860f3c89a33324d4152ae8 has the main `ScreenshotTest` class with the integration.

**Comment by NapasPayu** [comment]
@alexvanyo I couldn't make it work. I'd be great if you can share all the related classes or a sample repo.

**Comment by alexvanyo** [comment]
https://github.com/android/nowinandroid/pull/101 has a full PR in a project with the setup with Paparazzi for reference!

**Comment by davidvavra** [comment]
Thanks @alexvanyo, I created a full-fledged example including CI integration based on your work:

https://github.com/davidvavra/showkase-screenshot-tests

And I wrote an article about it:
https://proandroiddev.com/no-emulator-needed-for-screenshot-tests-of-compose-previews-on-ci-d292fa0eb26e

**Comment by vinaygaba** [comment]
A sample implementation has also been added to Showkase itself for your reference

**Comment by vinaygaba** [comment]
I've just started working on an artifact that makes it trivial to have a Showkase + Paparazzi setup for your codebase. It essentially auto generates the Paparazzi test class that leverages Showkase. All you need is 3 lines of code. PR here in case you have feedback - https://github.com/airbnb/Showkase/pull/294
