### ISSUE TITLE
Order parameter in showkase annotation

### ISSUE THREAD

**Issue by themanol** [airbnb/Showkase#215]
Right now all the elements are shown alphabetically inside the groups.

Do you think we can add an optional parameter 'order' and we sort the elements based on this parameter?

**Comment by themanol** [comment]
I open the https://github.com/airbnb/Showkase/pull/217 for adding this feature

**Comment by vinaygaba** [comment]
Showkase exposes all your previews that it collects through the Showkase.getMetadata() function (more info here - https://github.com/airbnb/Showkase#5-showkase-object). Using this metadata object, it would be trivial to create your own browser that behaves exactly how you want it to behave. For the extremely custom use cases, I feel like that would be a better option as opposed to expanding the public API.
