### ISSUE TITLE
Open component menu directly in case of not having Typography and colours

### ISSUE THREAD

**Issue by themanol** [airbnb/Showkase#221]
When the project doesn't have typography and colours would be great to open directly the component menu.
In this way we can save a click and avoid showing these 0 items list.

![Screenshot 2022-02-15 at 11 42 47](https://user-images.githubusercontent.com/4733008/154045848-64d28000-2b86-4662-a962-f3507d91db9a.png)

**Comment by themanol** [comment]
Possible solution:
https://github.com/airbnb/Showkase/pull/222

**Comment by vinaygaba** [comment]
#222 has merged!
