### ISSUE TITLE
doesn't support @Composables with default params

### ISSUE THREAD

**Issue by kenyee** [airbnb/Showkase#224]
Hopefully this is enough of a stacktrace with beta12:

```
error: com.airbnb.android.showkase.processor.exceptions.ShowkaseProcessorException: Make sure that the @Composable functions that you annotate with the Preview annotation only have a single parameter that is annotated with @PreviewParameter.
  	at com.airbnb.android.showkase.processor.logging.ShowkaseValidator.validateComponentElement$showkase_processor(ShowkaseValidator.kt:59)
Supported source version 'RELEASE_8' from annotation processor 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' less than -source '11'

  	at com.airbnb.android.showkase.processor.ShowkaseProcessor.processPreviewAnnotation(ShowkaseProcessor.kt:101)
  	at com.airbnb.android.showkase.processor.ShowkaseProcessor.processComponentAnnotation(ShowkaseProcessor.kt:75)
com.airbnb.android.showkase.processor.exceptions.ShowkaseProcessorException: Make sure that the @Composable functions that you annotate with the Preview annotation only have a single parameter that is annotated with @PreviewParameter.

  	at com.airbnb.android.showkase.processor.ShowkaseProcessor.process(ShowkaseProcessor.kt:57)
  	at com.airbnb.android.showkase.processor.BaseProcessor.internalProcess(BaseProcessor.kt:96)
  	at com.airbnb.android.showkase.processor.BaseProcessor.process(BaseProcessor.kt:64)

```

**Comment by vinaygaba** [comment]
This also tells me I should add the name of the function in the error. Should make debugging easier 😅

**Comment by kenyee** [comment]
yesss....please add the name of the function :-)

I just hooked the library up at this point (I haven't added @Preview anywhere...changes are literally just adding the kapt/impl so far)....what it's trying to look at I have no clue 🤷 

I did add it to one composable and oddly get the same error...
```
@ShowkaseComposable(name = "Inline Callout", group = "Callout")
@Composable
fun InlineCalloutShowkase() {
    InlineCalloutGallery()
}
```

**Comment by vinaygaba** [comment]
@kenyee Showkase does have first class support for @Preview (the Android Studio previews). Do you happen to have those at all in the codebase?

**Comment by kenyee** [comment]
ahhh...yes.  Those are there.

**Comment by kenyee** [comment]
Found it I think...the other previewed ones just have a single modifier param that's standard...this one is:
```
@Preview
@Composable
fun ModalGripper(
    width: Dp = 35.dp,
    height: Dp = 5.dp,
    modifier: Modifier = Modifier,
    color: Color = HorizonColor.Gray50
) {
```

**Comment by kenyee** [comment]
hmm...seems like all these need @PreviewParameter as well?
```
@Preview
@Composable
fun Home(modifier: Modifier = Modifier) {
```

**Comment by vinaygaba** [comment]
@kenyee Are you able to see these previews in Android Studio? I think these shouldn't work even in Android Studio

**Comment by kenyee** [comment]
@Preview works in AS w/ default params.
Showkase needs each of these annotated w/ @PreviewParameter?

**Comment by vinaygaba** [comment]
@kenyee Interesting! This might be a recent change. When I first wrote Showkase, this wasn't how Android Studio previews worked (although I should add that I first wrote it in 2020 so this could've certainly changed 😅). I'll see if there's a way for me to add support for this 🤔

**Comment by vinaygaba** [comment]
Showkase currently only supports a single param and that too only if its a PreviewParameter.

**Comment by kenyee** [comment]
makes sense...thanks 😄

**Comment by vinaygaba** [comment]
@kenyee The stopgap solution would be to just wrap these methods inside a function that doesn't accept parameters. Definitely not ideal but unblocks you..

```
fun ModalGripperPreview() {
    ModalGripper()
}
```

As I think more about it, I think it should be straightforward to add this functionality (support for functions with default params). Will keep you posted!

**Comment by kenyee** [comment]
Found another @Preview related bug....if you comment out @Preview for a composable, the codegen didn't understand that it's no longer there, so you get an error like:
"Unresolved reference: HomePreview" in ShowkaseHorizonModuleCodegen.kt
Have to do a clean and then rebuild.

**Comment by vinaygaba** [comment]
@kenyee Alright the PR to add support for this is up - https://github.com/airbnb/Showkase/pull/228
