### ISSUE TITLE
StyleName is not working

### ISSUE THREAD

**Issue by lepicekmichal** [airbnb/Showkase#231]
StyleName is not working, not even example. Getting just one preview, first one, inside browser activity.

Version: beta12

```
// Actual component
@Composable
fun CustomButton(
    size: ButtonSize,
    ...
)

// Previews
@ShowkaseComposable(name = "CustomButton", group = "Buttons", defaultStyle = true)
@Composable
fun Preview_CustomButton_Large() {
    CustomButton(size = ButtonSize.Large)
}

@ShowkaseComposable(name = "CustomButton", group = "Buttons", styleName = "Medium size")
@Composable
fun Preview_CustomButton_Medium() {
    CustomButton(size = ButtonSize.Medium)
}

@ShowkaseComposable(name = "CustomButton", group = "Buttons", styleName = "Small size")
@Composable
fun Preview_CustomButton_Small() {
    CustomButton(size = ButtonSize.Small)
}
```

**Comment by lepicekmichal** [comment]
Taking bug, just noticed how it works. Could you maybe just make it more obvious that mutliple styles are nested? I couldn't tell it's after click that I see all options.

Array of styles question stands :)

**Comment by vinaygaba** [comment]
@lepicekmichal  I added some more documentation in this section of the README. Do take a look and let me know if this isn't clear - https://github.com/airbnb/Showkase#representing-component-styles-in-showkase
