### ISSUE TITLE
How is versioning managed

### ISSUE THREAD

**Issue by marcorighini** [airbnb/Showkase#236]
What's the current agreement on versioning? 
Are new versions expected with a predefined cadence or are we working with scoped milestones?
In case we are not going to release frequently, a snapshot build could help, enabling the possibility to integrate the latest changes.

**Comment by vinaygaba** [comment]
I just published the latest release - sorry about not doing this sooner. I didn't realize how long it had been even though we had made some improvements - https://github.com/airbnb/Showkase/releases/tag/1.0.0-beta13

There's no fixed cadence. Ideally every time there's a few meaningful improvement', I'd like to see a release. Sometimes this happens even for a single change if necessary.
