### ISSUE TITLE
Showkase browser doesn't work with empty @Preview BackHandler

### ISSUE THREAD

**Issue by ReginFell** [airbnb/Showkase#247]
If you have `BackHandler` which does nothing inside @Preview it breaks navigation for Showkase browser 

Snippet to reproduce: 
```
@Composable
fun ContentScreen(
    viewModel: ContentViewModel = androidx.lifecycle.viewmodel.compose.viewModel(),
) {
    Content(onBack = viewModel::onBack)
}

@Composable
fun Content(onBack: () -> Unit) {
    BackHandler(onBack = onBack)
}

@Preview
@Composable
fun ContentPreview() {
    Content(
        onBack = {},
    )
}

```

If you open `ContentPreview` from Showkase browser, it will not be possible to navigate back

**Comment by vinaygaba** [comment]
@ReginFell I was able to repro and have a fix pushed for it
