### ISSUE TITLE
Docs: useKsp gradle flag doesn't seem to be relevant

### ISSUE THREAD

**Issue by micHar** [airbnb/Showkase#251]
The README mentions that in order to use ksp, one should use a `-PuseKsp=true` flag in the gradle command that builds the app. I just checked and it doesn't seem to be necessary.
```
./gradlew sample:clean sample:build -i -PuseKsp=true
```

 It is used by the showkase sample app, but it's misleading to include it in the installation instruction.

**Comment by vinaygaba** [comment]
Yeah you are right that I needed it only in the sample case since I've set up both the annotation processors there. The library itself isn't using the flag, just the sample is. I will remove it from the documentation. Thanks for flagging it!
