### ISSUE TITLE
Throwing exception even when no ShowkaseComposable annotated function is private or internal

### ISSUE THREAD

**Issue by iamutkarshtiwari** [airbnb/Showkase#260]
I have a multi module android project where I am trying to integration showkase library with paparazzi to setup screenshot testing.

I have made sure to replace all my `@Preview` annotated composable functions with `@ShowkaseComposable` and they all are public. However, when build the project, I get this Exception:

```kotiln
com.airbnb.android.showkase.processor.exceptions.ShowkaseProcessorException: The methods annotated with ShowkaseComposable can't be private as Showkase won't be able to access them otherwise.
```

This is blowing my mind away because I have checked several times and all those functions are public. I even tried a clean rebuild, but to no avail.
Verions: `1.0.0-beta14`

**Comment by iamutkarshtiwari** [comment]
My bad. I didn't sleep well so my brain wasn't functioning optimally. There was a private method which I overlooked.

**Comment by Odaym** [comment]
you're not wrong :) I just tried this library in an app that doesn't have any Previews, I still get this message :D
