### ISSUE TITLE
[Request] the test case names to be easier to recognize.

### ISSUE THREAD

**Issue by oh-naoki** [airbnb/Showkase#269]
Thank you for the great library! ☺️ 

I'm using Showkase for Screenshot testing and running on Firebase test lab.
Showkase generates a test case like the following for each Preview.
If there is a Preview that renders a Dialog, the test fails, but it is difficult to identify which Preview failed at that time.
It would be helpful if you could assign name and group to the test case name! 🙇‍♂️ 

``` kt
@Preview(name = "Sample1", group = "Sample")
@Composable
fun SamplePreview() {
    Column {
        ...
    }
}
```

↓ will generate by Showkase

``` kt
@Test
public fun composable_screenshot_test_0(): Unit {
  takeComposableScreenshot(Showkase.getMetadata().componentList[0])
}
```

**Comment by vinaygaba** [comment]
This was addressed by this PR - https://github.com/airbnb/Showkase/commit/c7a8c5e0567ef3778110610dbece46d67a04c200

You should now have more information about which preview failed when the test fails
