### ISSUE TITLE
Multi-modules project : how to avoid public visibility for @Preview?

### ISSUE THREAD

**Issue by borsini** [airbnb/Showkase#271]
The documentation [states that](https://github.com/airbnb/Showkase#4-showkaseroot) 
>The root module is the main module of your app that has a dependency on all other modules in the app. This is relevant because we generate the Showkase related classes in the package of the root module and we need to be able to access the UI elements across all the sub modules. This is only possible from the root module as it typically has a dependency on all the sub-modules.

- Does it mean that we can only have one `@ShowkaseRootModule` per project?

- Setting all the composables to render with a public visibility adds unnecessary items to the auto-completion list. Do you have an idea to help mitigate this?

Many thanks!

**Comment by iamutkarshtiwari** [comment]
HI @borsini, thanks for raising this! I [mentioned](https://github.com/airbnb/Showkase/issues/250#issuecomment-1248874672) something similar couple of days back.

**Comment by borsini** [comment]
Thanks @iamutkarshtiwari , that would be an alternative. We ended up excluding our Previews from the IDE autocompletion-list.

Regarding my first question, does anyone have a clue? maybe @vinaygaba ? Having multiple ShowkaseRoot would help isolate previews and keep them internal
> Does it mean that we can only have one @ShowkaseRootModule per project?

**Comment by elcolto** [comment]
Also looking for a solution for this problem.

Would it be possible to add a configuration option to opt-out from auto including `@Preview` annotation from ShowkaseModule? To just include `@ShowkaseComposable(skip = false)` annotated functions?

**Comment by vinaygaba** [comment]
A recent change that I made now enables creating previews that are `internal` instead of `public`. It's part of the `1.0.0-beta17` release. I think this should fix the problem that you originally raised. What do you think @borsini?

**Comment by vinaygaba** [comment]
Going to close this as the `1.0.0-beta17` release fixes this issue 🥳
