### ISSUE TITLE
ShowkaseProcessorException

### ISSUE THREAD

**Issue by Faiz882** [airbnb/Showkase#282]
can you please help me to resolve this issue ?
com.airbnb.android.showkase.processor.exceptions.ShowkaseProcessorException: The methods annotated with ShowkaseComposable can't be private as Showkase won't be able to access them otherwise.

**Comment by oas004** [comment]
From the picture it might be this issue : https://github.com/airbnb/Showkase/pull/258

This will be released in the next release as well I believe.

However, it is hard to tell without seeing the code. If you provide a sample I can have a look of course 😊

**Comment by Faiz882** [comment]
Do you think it's due to multiple flavors ?

**Comment by Faiz882** [comment]
Actually I am using 4 different flavors e.g patient, doctor, patientBeta and doctorBeta. 
Current my build variant is **patient** ,  so is there any possibility to occurring this issue due to multiple flavors? I have used same code in **testSampleProject**. Everything is working fine in that project.

**Comment by Faiz882** [comment]
![image](https://user-images.githubusercontent.com/29184029/206283435-199570ed-8786-485b-be18-14ec93d88075.png)

**Comment by oas004** [comment]
I think it is the issue I posted because of the indentation 😊

**Comment by Faiz882** [comment]
Okay Thank you 
Noted
