### ISSUE TITLE
Showkase.getMetadata() not generated after build

### ISSUE THREAD

**Issue by hamzabintariq123** [airbnb/Showkase#283]
Hi all,

I am following this article https://proandroiddev.com/no-emulator-needed-for-screenshot-tests-of-compose-previews-on-ci-d292fa0eb26e to test UI without using running emulator .

I have integrated showcase in a dummy project and it runs fine, but when I try to write a test this Showkase.getMetadata() is not generated in the tests ? 

![Screenshot 2022-12-08 at 1 10 34 AM](https://user-images.githubusercontent.com/20186721/206285436-d1c87883-3487-499a-a2ac-8dadaa4f7f81.png)

**Comment by alvindizon** [comment]
How did you solve this?
