### ISSUE TITLE
[Request] Provide dark background for rendering Dark mode previews

### ISSUE THREAD

**Issue by trod-123** [airbnb/Showkase#289]
Apologies if this is already available, I have not seen any callouts for this in the README.

Basically, the request is to render a black card background in the `[Dark Mode]` preview generated by Showkase.

I defined my own Preview annotation which provides both the Light and Dark versions of content.
```kotlin
@Preview(
    name = "Light theme",
    showBackground = true,
    backgroundColor = 0xFFFFFFFF,
    uiMode = UI_MODE_NIGHT_NO
)
@Preview(
    name = "Dark theme",
    showBackground = true,
    backgroundColor = 0xFF000000,
    uiMode = UI_MODE_NIGHT_YES
)
internal annotation class PreviewDefaults
```

Which generates the following:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/11514412/208006849-40cc2146-8b4c-4cc7-a5bf-a5378ebb11c5.png">

It would be great to have a similar functionality provided by Showkase out of the box. As it stands, the previews look like the following - note the content text in `[Dark Mode]` can't be read because the background is white, and not black.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/11514412/208006902-51bf92f1-278d-4969-9afe-b0d1402a5011.png">

As a workaround, I can wrap my preview content in a box that provides a background (with additional padding so we can see the dashed borders), but I do not think I should do this every time.

```kotlin
@ShowkaseComposable(
    name = PREVIEW_NAME,
    group = GROUP_CARD,
    defaultStyle = true,
)
@PreviewDefaults
@Composable
internal fun DashedCardPreview() {
    MyTheme {
        Box(
            modifier = Modifier
                .background(color = MyTheme.colors.background.page.default)
                .padding(16.dp)
        ) {
            DashedCardSample()
        }
    }
}
```

<img width="454" alt="image" src="https://user-images.githubusercontent.com/11514412/208007995-1fa14207-1b33-46c3-9d0f-315494d3db17.png">

**Comment by vinaygaba** [comment]
Since these are properties of the `@Preview` annotation itself, I'm open to adding them to `@ShowkaseComposable` and/or honoring what's passed as part of `@Preview`. For prioritization sake, I'm curious to see if more people would benefit from this change.

**Comment by micHar** [comment]
Interested!

**Comment by eboudrant** [comment]
Interested too

**Comment by kikin81** [comment]
➕

**Comment by Alton09** [comment]
+1 this would be a great to have!

**Comment by drinkthestars** [comment]
+100 this would be great to have when combining with screenshot testing for light/dark modes

**Comment by kmalmur** [comment]
me too

**Comment by yerdaulet1991** [comment]
interested
