### ISSUE TITLE
Provide the custom background color from @Preview in the metadata

### ISSUE THREAD

**Issue by micHar** [airbnb/Showkase#295]
If I have a white component, in my previews I show it against non-white background with sth like `@Preview(showBackground = true, backgroundColor = 0xFFF4F9FF)`. Would be great if Showkase read that and added that to the metadata (and of course that could be used when rendering the default showkase gallery).

```
@ShowkaseComposable(name = "Basic card", group = "Cards")
@Preview(showBackground = true, backgroundColor = 0xFFF4F9FF)
@Composable
fun MyCardPreview() {
    MyTheme {
        MyCard {
            Text(text = "Capybaras are the best!")
        }
    }
}
```

That's probably not too hard to do, let me know if you would like a PR for that.

**Comment by vinaygaba** [comment]
Duplicates #289
