### ISSUE TITLE
Fast allow to download and look at it

### ISSUE THREAD

**Issue by b0r1ngx** [airbnb/Showkase#297]
Why didn't post an .apk fle at assets in releases, to make it fast to check out, what we can do with this application

**Comment by vinaygaba** [comment]
I'm not sure I follow your question. Are you saying that you would like an apk of the ShowkaseBrowser? It's possible to do that if you'd like, just how you do it with any other app. ShowkaseBrowser is just an activity so you can wrap it in side any app shell and do an apk release if you'd like.
