### ISSUE TITLE
Maven dependencies don't work with renovatebot

### ISSUE THREAD

**Issue by barry-irvine** [airbnb/Showkase#308]
If I look at the [Maven repository] (https://mvnrepository.com/artifact/com.airbnb.android/showkase-processor) `1.0.0-kotlin1.5.30-1` appears in blue and above the red `1.0.0-beta17` version.

So even though this is much newer, Renovate Bot tries to upgrade the app to the "stable" Kotlin1.5.30 release. Is it possible to rectify this so that renovate bot and (presumably) Dependabot work properly?

**Comment by vinaygaba** [comment]
@barry-irvine Yes, this was a mistake on my part when I was testing something. I plan to fix this in the next release

**Comment by vinaygaba** [comment]
This is fixed with the latest release
