### ISSUE TITLE
Custom MutliPreview annotations don't respect skipPrivatePreviews 

### ISSUE THREAD

**Issue by undermark5** [airbnb/Showkase#312]
Issue #233 and associated resolution PR #303 fail to properly handle MultiPreview annotations.

While trying to configure this in my project, I have a few custom multi preview annotations that are added to some private functions. The KSP step complains stating that the methods can't be private and that if I want it to skip them, I must configure the ksp arguments, which I have done, so the message is actually in error and the multipreview on private methods should be skipped.

**Comment by oas004** [comment]
Thanks for the report! I tested it out now, and I can reproduce it. Will try to fix it as fast as possible.

**Comment by jd565** [comment]
@oas004 Any idea when this will get into a release? We are hit this problem when updating to beta 18 and it causes an error in ksp and the build fails.

**Comment by oas004** [comment]
@jd565 I think that will be up to @vinaygaba and Airbnb when they will release a new version :)

**Comment by SumeraMartin** [comment]
@vinaygaba Hi, since this is merged, are you planning to release new version? I would be very happy since this is something that is blocking me currently in my project 🙏
