### ISSUE TITLE
Unresolved references when @Previews are renamed / deleted

### ISSUE THREAD

**Issue by carlosmuvi-stripe** [airbnb/Showkase#316]
Hi! We're using Showkase with Paparazzi to run screenshot testing on our previews.  

When a Preview gets renamed or deleted, the corresponding `ShowkaseCodegen` file for that module fails with unresolved reference errors instead of being regenerated. Cleaning does not help, the only solution found so far involves manually removing the outated preview references from the generated file.

See an example below after renaming the @Preview's group of a given screen. 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/99293320/230163641-18191a04-e08b-4d44-b81c-d63e7f5fa103.png">

```
stripe/stripe-android/financial-connections/build/generated/source/kapt/debug/com/stripe/android/financialconnections/FinancialConnectionsShowkaseRootModuleCodegen.kt:29:63 Unresolved reference: comstripeandroidfinancialconnectionsfeaturesresetResetDefault
```
Some references to our configuration:

- [Paparazzi tests](https://github.com/stripe/stripe-android/blob/c267e1bb1448027727ce150aaa9e27f48e839084/financial-connections/src/test/java/com/stripe/android/financialconnections/screenshottests/FinancialConnectionsShotShowkaseScreenshotTest.kt#L23).
- [Showkase module](https://github.com/stripe/stripe-android/blob/73d7f24b46df6a971f65ddc79fb4e640291d8e55/financial-connections/src/debug/java/com/stripe/android/financialconnections/FinancialConnectionsShowkaseRootModule.kt#L7).
 
Thank you!

**Comment by carlosmuvi-stripe** [comment]
yes : )

**Comment by vinaygaba** [comment]
Unfortunately this is a known issue that we suspect has something to do with a kapt bug. This is not an issue when you use Showkase with `ksp` and has been working really well for us + other users of this library as well.

**Comment by vinaygaba** [comment]
Closing as there's a duplicate issue currently open #273
