### ISSUE TITLE
Allow a way to configure ignoring @Preview

### ISSUE THREAD

**Issue by undermark5** [airbnb/Showkase#318]
It would be wonderful if there was a way to disable generating elements for all items annotated with `@Preview` regardless of their visibility modifiers. Allowing the codebase owners to determine which annotation should be used.

Theoretically one possible way to do this could actually to be via providing a way to configure a list of annotations (custom or builtin) that should generate elements for.

**Comment by vinaygaba** [comment]
One way in which you can do this today is to mark the @Preview functions that you don't need as private and then pass then leverage the `skipPrivatePreviews` flag

```
ksp {
 arg("skipPrivatePreviews", "true")
}

or

kapt {
 arguments {
  arg("skipPrivatePreviews", "true")
 }
}
```
