### ISSUE TITLE
clarity on usage of compose version.

### ISSUE THREAD

**Issue by karandeepsingh-cred** [airbnb/Showkase#319]
Hi,
is Shokwase compatible with the version mentioned on the home page? since it says 1.2.1 while 1.4 is there already. 😅

**Comment by designedbyz** [comment]
I'm on a team that has successfully used Showkase with Compose 1.3, and is now using it with Compose 1.4.

**Comment by vinaygaba** [comment]
I've updated the README to reflect the right version of Compose that Showkase is using
