### ISSUE TITLE
Supporting debugImplementation for the libraries

### ISSUE THREAD

**Issue by ssaxena01** [airbnb/Showkase#323]
Is there a plan to address this todo?
    // TODO(vinaygaba): Using debugImplementation was causing kapt related NonExistentClass errors.
    //  Figure out a way to enable using debugImplementation

I would like to not include this dependency for the release version of the app to keep the app size from increasing. Also, Showkase is only used internally on development builds. I'm seeing the kapt related NonExistentClass errors with the following code in a multi-module project.

```
debugImplementation(libs.showkase)
kaptDebug(libs.showkase.processor)

``` 
or
```
debugImplementation(libs.showkase)
kapt(libs.showkase.processor)
```

**Comment by vinaygaba** [comment]
@ssaxena01 Ignore the TODO, this is already supported today. Here's what you'd need

```
debugImplementation(libs.showkase)
kaptDebug(libs.showkase.processor)

implementation (libs.showkase.annotation)
```

The `showkase-annotation` artifact is super lightweight with just a couple annotations and no other logic. Let me know if you need any more information.
