### ISSUE TITLE
Release of version beta19

### ISSUE THREAD

**Issue by SumeraMartin** [airbnb/Showkase#332]
Hi, thank you for the work this is wonderful library. I would like to know if there are some plans to release beta19 with things like [this fix](https://github.com/airbnb/Showkase/issues/312) included which was merged two months ago. I understand that this is open source project but I would like to schedule some things related to this bug if I should try to find some workaround or if I will be able to use version with fix within few days-weeks-months.

Thank you

**Comment by vinaygaba** [comment]
A new release just went out - https://github.com/airbnb/Showkase/releases/tag/1.0.2
