### ISSUE TITLE
UI components are not showing up (yet groups are)

### ISSUE THREAD

**Issue by LeBar** [airbnb/Showkase#337]
In our Compose project, Showkase only shows component groups that change the title when clicked but nothing happens afterward (s. attached screenshot). We do have a multi-module project if that's relevant. There's no difference when using @ShowkaseComposable or @Preview and the group names are correctly shown in the Showkase overview.

Any known problems that might lead to this problem? 🤷🏻‍♂️

<img width="390" alt="before tap" src="https://github.com/airbnb/Showkase/assets/681301/7a950f90-bc6d-4004-8639-4cd0b5d772c8">
=>
<img width="390" alt="after tap" src="https://github.com/airbnb/Showkase/assets/681301/5edf897b-bb29-432d-8250-f85505db0eda">

**Comment by matejdro** [comment]
For us, updating `androidx.navigation` from `2.5.3` to `2.6.0` seems to have triggered this.

**Comment by LeBar** [comment]
That fixed it, thank you so much! 🙏🏻

**Comment by LeBar** [comment]
Showkase doesn't work with `androidx.navigation` `2.5.3`. `2.5.0` as well as `2.7.0(beta02)` work as expected.

**Comment by matejdro** [comment]
I wouldn't close this issue, I think it should at least be documented somewhere, that navigation 2.6.0 breaks it.
