### ISSUE TITLE
PreviewParameters don't work with Kotlin 1.9

### ISSUE THREAD

**Issue by barry-irvine** [airbnb/Showkase#343]
When upgrading to Kotlin 1.9, any functions that have a preview parameter fail to process correctly.

`com.airbnb.android.showkase.processor.exceptions.ShowkaseProcessorException: Make sure that the @Composable functions that you annotate with the ShowkaseComposable annotation only have a single parameter that is annotated with @PreviewParameter.
`

This is what my function looks like (and it works fine with Kotlin 1.8.22).

```
@ShowkaseComposable(name = "Small Badge", "Attraction List Item", "Loaded")
@Composable
fun ShowkasePreviewAttractionListItemSmallBadge(
    @PreviewParameter(
        AttractionSummaryPreviewParameterProvider::class,
        limit = 1
    ) attraction: Attraction
) {
    MyTheme {
        MyComposable(attraction)
    }
}
```

**Comment by k0siara** [comment]
Any updates on this one?
