### ISSUE TITLE
old account label bypassing all fraud measures

### ISSUE THREAD

**Issue by nikhilmiddha** [airbnb/Showkase#359]
old account label bypassing all fraud measures
airbnb kotlin upgrade to true time 
sift implementation with new rules
2fa on new added cards specially for (fcu banks)
amount review above 500$ booking request
java-script enable request with headers

**Comment by vinaygaba** [comment]
I'm not sure I follow what you are trying to say. It looks unrelated to Showkase in any case. For general Airbnb issues, please use Customer Support from the main site.
