### ISSUE TITLE
Root module codegen preventing incremental compilation for KSP

### ISSUE THREAD

**Issue by joshdmiller5** [airbnb/Showkase#373]
Somewhat similar to #322, we've been encountering the following warning when running our custom build jobs on Jenkins:

``` w: [ksp] No dependencies reported for generated source ShowkaseRootModuleCodegen.kt which willprevent incremental compilation.```

It appears that similar KSP issues have been reported https://github.com/google/dagger/issues/4182, but curious if there are any suggestions for Showkase workarounds in the meantime as our app heavily relies on incremental compilation?

Currently failing with the following versions:
```
kotlin = "1.9.21"
ksp = "1.9.21-1.0.16"
showkase = "1.0.2"
dagger = "2.49"
```

**Comment by vinaygaba** [comment]
Interesting. I'm going to try investigating this shortly.

**Comment by joshdmiller5** [comment]
Thank you! Let me know if there is any additional information you need

**Comment by joshdmiller5** [comment]
Following up here just to add a little bit more information:

-  Currently, our application uses KAPT for all other annotation processing, including dagger. However, I wanted to use KSP for Showkase to avoid the root module regen issues mentioned in previous issue threads. Not sure if this could be the culprit, but worth noting.
- The dagger issue linked above has been updated, recommending dagger and dagger-compiler be added as dependencies to all feature modules firing this warning. Trying that on my end, however, did not seem to have any effect.
