### ISSUE TITLE
Compose 1.4.2+ support

### ISSUE THREAD

**Issue by skylerreimer** [airbnb/Showkase#382]
Hey there! 

I'm working on a design system within Amazon that vends a Compose library. We love Showkase for helping us during development and with screenshot testing. Unfortunately we have some internal users who would like to use a higher version of Compose than `1.4.2`. 

What is the lift to bump the version? Our internal build system doesn't play well with external dependencies sometimes. Happy to possibly do the work if we can guarantee it gets released sooner rather than later.

**Comment by vinaygaba** [comment]
Have just put up a PR that show give you what you need!
